# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: railsgirls
  username: root
  host: localhost
  password:
  socket: /private/tmp/mysql.sock
  variables:
     sql_mode: TRADITIONAL

development:
  <<: *default
  ddapter: mysql2
  pool: 5
  timeout: 5000
  database: railsgirls
  username: root
  host: localhost
  password:
  socket: /private/tmp/mysql.sock
  variables:
     sql_mode: TRADITIONAL

